spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kiwi_db?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: kiwi
    password: kiwi1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  security:
#    user:
#      name: admin
#      password: admin1234
server:
  port: 8888