spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kiwi_db?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    username: kiwi
    password: kiwi1234
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update # 自动更新
    show-sql: true  # 日志中显示sql语句
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8888
  springfox:
    documentation:
      swagger-ui:
        enabled:true